Django-Projects/django_chat/ChatServerPlayground/ChatServerPlayground/ChatServerPlayground/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from personal.views import (
    home_screen_view,
)

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('account/', include('account.urls', namespace="account")),
    path('admin/', admin.site.urls),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('search/', account_search_view, name="search"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Projects/django_chat/ChatServerPlayground/ChatServerPlayground/account/urls.py
from django.urls import path

from account.views import (
    account_view,
    edit_account_view,
)

app_name = "account"

urlpatterns = [
    # path('<user_id>/', account_view, name="view"),
    path('<user_id>/', account_view, name='view'),
    path('<user_id>/edit/', edit_account_view, name='edit'),
]

Django-Projects/django_chat/ChatServerPlayground/ChatServerPlayground/templates/snippets/base_css.html
<style type="text/css">
    head{
        font-family: "Segoe UI";
        font-weight: 380;
    }

    footer {
        font-family: "Segoe UI";
        font-weight: 380;
    }

    body {
        background-color: #f2f2f2;
        font-family: "Segoe UI";
        font-weight: 380;
    }

    :root {
        --main-background-color: #f2f2f2;
        --dark-background-color: #a2a2a2;
        --secondary-text-color: #808080;
        --light-primary-text-color: #008044;
    }
</style>

Django-Projects/django_chat/ChatServerPlayground/ChatServerPlayground/templates/snippets/base_js.html
<script text="text-javascript">
    
</script>

Django-Projects/django_chat/ChatServerPlayground/ChatServerPlayground/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>
<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto">Codingwithmitch Chat</p>
</div>

Django-Projects/django_chat/ChatServerPlayground/ChatServerPlayground/templates/snippets/header.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script> -->
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<div class="d-flex p-3 px-md-4 mb-4 bg-white border-bottom shadow-sm">

	<!-- MEDIUM+ screens -->

	<!-- col1 -->
	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<!-- col2 -->
		<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search...">
		</form>

		<!-- col3 -->
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav>
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft show p-2">
					<div class="d-flex flex-row">

						<!-- chat notifications -->
						<div class="d-flex flex-row">
							<div class="btn-group dropleft">
								<div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_chat_notification_dropdown_toggle"
								data-toggle="dropdown">
								<span id="id_chat_notifications_count" class="notify-badge"></span>
								<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
								<div class="dropdown-menu scrollale-menu" aria-labelledby="id_chat_notification_dropdown_toggle" id="id_chat_notifications_container">

								</div>
								</div>

							</div>
						</div>

						<!-- general notifications -->
						<div class="d-flex flex-row">
							<div class="btn-group dropleft">
								<div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_notification_dropdown_toggle"
								data-toggle="dropdown">
								<span id="id_general_notifications_count" class="notify-badge"></span>
								<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
								<div class="dropdown-menu scrollale-menu" aria-labelledby="id_notification_dropdown_toggle" id="id_chat_notifications_container">

								</div>
								</div>

							</div>
						</div>

						<!-- account -->
						<div class="btn-group dropleft">
							<img src="{{ request.user.profile_image.url }}" alt="codingwithmitch logo" width="40" height="40" class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" araia-haspopup="true" araia-expanded="false">
							<div class="dropdown-menu" araia-labeledby="id_profile_links">
								<a href="{% url 'account:view' user_id=request.user.id  %}" class="dropdown-item">Account</a>
								<a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
							</div>
						</div>

					</div>
					<ul class="dropdown-menu">
					</ul>
				</div>
				{% else %}
					<a href="{% url 'login' %}" class="p-2 text-dark">Login</a>
					<a href="{% url 'register' %}" class="btn-outline-primary" >Register</a>
				{% endif %}
			</nav>
		</div>
	</div>
	<!-- END MEDIUM+ SCREENS -->
	<!-- SMALL- screens -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">
		<!-- row 1 -->
		<h5 class="font-weight-normal">
			<a href="{% url 'home' %}" class="p-2 text-dark"></a>
		</h5>

		<!-- row 2 -->
		<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search...">
		</form>

		<!-- row 3-->
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav>
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<!-- account -->
						<div class="btn-group dropleft">
							<img src="{{ request.user.profile_image.url }}" alt="codingwithmitch logo" width="40" height="40" class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" araia-haspopup="true" araia-expanded="false">
							<div class="dropdown-menu" araia-labeledby="id_profile_links">
								<a href="{% url 'account:view' user_id=request.user.id %}" class="dropdown-item">Account</a>
								<a href="{% url 'logout' %}" class="dropdown-item" >Logout</a>
							</div>
						</div>
 
					</div>
					<ul class= "dropdown-menu">
					</ul>
				</div>
				{% else %}
					<a href="{% url 'login' %}" class="p-2 text-dark" >Login</a>
					<a href="{% url 'register' %}" class="btn-outline-primary m-2" >Register</a>
				{% endif %}
			</nav>
		</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>

<script type="text/javascript">
	function executeQuery() {
		var query = document.getElementById("id_q_small").value;
		if (query == "") {
			query = document.getElementById("id_q_large").value;
		}

		window.location.replace("{% url 'search' %}?q=" + query);
		return false;
	}
</script>